version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qWERTY1@
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    container_name: postgres
    ports:
      - '5432:5432'
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 3
  rabbitmq:
    image: rabbitmq:3.12.12-management
    restart: always
    container_name: rabbitmq
    hostname: 'rabbitmq'
    ports: 
            - 5672:5672
            - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 4s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charger
    environment:
      - DB_NAME=postgres
      - DB_TYPE=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qWERTY1@
      - DB_HOST=db
      - CLOUDAMQP_URL=amqp://rabbitmq:5672
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        