version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=qWERTY1@
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    container_name: postgres
    ports: 
      - '5432:5432'
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 3
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: charger
    environment:
      - DB_NAME=postgres
      - DB_TYPE=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qWERTY1@
      - DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src